apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
  namespace: devops
  labels:
    app: monitoring-pod
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:latest
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
        - containerPort: 9090
      volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
    - name: grafana
      image: grafana/grafana:latest
      env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
      ports:
        - containerPort: 3000
  volumes:
    - name: prometheus-config
      configMap:
        name: prometheus-config
